name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: '55 23 * * 0'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: general.svg
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          config_timezone: Europe/Berlin
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, vue, scala
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_topics: yes
          config_order: base.header, isocalendar, languages, topics, lines
